trophies:
  - title: "My Custom Trophy"
    description: "This is a custom trophy that I created"
    icon: "fa-code"
    theme: "darkhub"
    rank: "SECRET"
  - title: "Another Custom Trophy"
    description: "This is another custom trophy that I created"
    icon: "fa-star"
    theme: "calm"
    rank: "S"
  - title: "Super Secret Trophy"
    description: "This is a super secret trophy that only a few people can get"
    icon: "fa-user-secret"
    theme: "darkhub"
    rank: "SSS"
  - title: "Legendary Trophy"
    description: "This trophy is only for legends"
    icon: "fa-trophy"
    theme: "calm"
    rank: "RANK6"
  - title: "Elite Trophy"
    description: "This trophy is for the elite few"
    icon: "fa-users"
    theme: "darkhub"
    rank: "RANK7"
  - title: "Special Trophy"
    description: "This is a special trophy that not many people have"
    icon: "fa-gift"
    theme: "calm"
    rank: "RANK8"
