trophies:
  - title: "My Custom Trophy"
    description: "This is a custom trophy that I created"
    icon: "fa-code"
    theme: "darkhub"
    rank: "SECRET"
  - title: "Another Custom Trophy"
    description: "This is another custom trophy that I created"
    icon: "fa-star"
    theme: "calm"
    rank: "S"
